version: '3'
services:
  mongo:
    image: mongo:4
    container_name: babymonkeybot-mongo
  core:
    build:
      context: .
      dockerfile: Dockerfile
    image: babymonkeybot
    entrypoint: bash docker/launch.sh
    ports:
      - "5000:5000"
      - "5100:5100"
    environment:
      MONGODB_URI: mongodb://babymonkeybot-mongo/babymonkeybot
    env_file:
      - .env
    volumes:
      - .:/usr/src
    links:
      - mongo
    container_name: babymonkeybot
